### ISSUE TITLE
怎么使用沙盒图片，直接使用渲染有问题啊

### ISSUE THREAD

**Issue by lizhen01** [451518849/VRPanoramaKit#1]
在吗？我直接使用沙盒图片进行替换 全景图渲染会有问题。

**Comment by 451518849** [comment]
@lizhen01 什么问题？

**Comment by lizhen01** [comment]
这个是我本地图片的问题，我还想请教一个问题：使用openGL 怎么自己定义全景图片的初始显示位置？
![image](https://user-images.githubusercontent.com/14814927/40907766-648b23c4-6817-11e8-9579-662d962adda0.png)
是这个方法吗？

**Comment by 451518849** [comment]
@lizhen01 不是，在GLKViewControllerDelegate中
